"""phase5 laboratory tests orders items samples results

Revision ID: 8587a225c814
Revises: 6ef9520c8b6d
Create Date: 2026-08-15 14:04:02.027566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8587a225c814'
down_revision: Union[str, None] = '6ef9520c8b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratory_tests',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('reference_range_low', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reference_range_high', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reference_range_text', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_tests_category'), 'laboratory_tests', ['category'], unique=False)
    op.create_index(op.f('ix_laboratory_tests_code'), 'laboratory_tests', ['code'], unique=True)
    op.create_table('laboratory_orders',
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('consultation_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ORDERED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='lab_order_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_orders_order_number'), 'laboratory_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_laboratory_orders_patient_id'), 'laboratory_orders', ['patient_id'], unique=False)
    op.create_table('laboratory_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('lab_test_id', sa.UUID(), nullable=False),
    sa.Column('test_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SAMPLE_COLLECTED', 'IN_PROGRESS', 'RESULT_ENTERED', 'VALIDATED', 'CANCELLED', name='lab_item_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_test_id'], ['laboratory_tests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['laboratory_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_order_items_order_id'), 'laboratory_order_items', ['order_id'], unique=False)
    op.create_table('laboratory_samples',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('sample_type', sa.Enum('BLOOD', 'URINE', 'STOOL', 'SWAB', 'OTHER', name='lab_sample_type'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['laboratory_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_samples_order_id'), 'laboratory_samples', ['order_id'], unique=False)
    op.create_table('laboratory_results',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('reference_range_display', sa.String(length=128), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entered_by_id', sa.UUID(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by_id', sa.UUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['laboratory_order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_results_order_item_id'), 'laboratory_results', ['order_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laboratory_results_order_item_id'), table_name='laboratory_results')
    op.drop_table('laboratory_results')
    op.drop_index(op.f('ix_laboratory_samples_order_id'), table_name='laboratory_samples')
    op.drop_table('laboratory_samples')
    op.drop_index(op.f('ix_laboratory_order_items_order_id'), table_name='laboratory_order_items')
    op.drop_table('laboratory_order_items')
    op.drop_index(op.f('ix_laboratory_orders_patient_id'), table_name='laboratory_orders')
    op.drop_index(op.f('ix_laboratory_orders_order_number'), table_name='laboratory_orders')
    op.drop_table('laboratory_orders')
    op.drop_index(op.f('ix_laboratory_tests_code'), table_name='laboratory_tests')
    op.drop_index(op.f('ix_laboratory_tests_category'), table_name='laboratory_tests')
    op.drop_table('laboratory_tests')
    # ### end Alembic commands ###
